[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[dev]
  command = "npm run dev:client"
  targetPort = 5173
  port = 8888
  publish = "dist"

[[redirects]]
  from = "/api/schedule"
  to = "/.netlify/functions/schedule"
  status = 200
